# Generated by Django 4.1.7 on 2023-03-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0003_alter_electronic_e_pname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronic',
            name='e_pbrand',
            field=models.CharField(choices=[('S', 'SYSKA'), ('L', 'LG'), ('W', 'Whirlpool'), ('B', 'Bajaj')], max_length=40),
        ),
    ]
