# Generated by Django 4.1.7 on 2023-03-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0004_alter_electronic_e_pbrand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronic',
            name='e_pname',
            field=models.CharField(choices=[('Tubelight', 'T'), ('Fridge', 'F'), ('Television', 'T'), ('Mixer', 'M')], max_length=40),
        ),
    ]
