# Generated by Django 4.1.7 on 2023-03-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Electronics', '0005_alter_electronic_e_pname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronic',
            name='e_pname',
            field=models.CharField(choices=[('T', 'Tubelight'), ('F', 'Fridge'), ('T', 'Television'), ('M', 'Mixer')], max_length=40),
        ),
    ]
