# Generated by Django 4.1.7 on 2023-03-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wadrobe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_wname', models.CharField(max_length=40)),
                ('w_wbrand', models.CharField(choices=[('H', 'Horse_villa'), ('D', 'Denim')], max_length=50)),
                ('w_wid', models.IntegerField()),
                ('w_wprice', models.FloatField()),
                ('w_wwarr', models.IntegerField()),
            ],
            options={
                'db_table': 'wadrobe',
            },
        ),
    ]
